import math

# Screen
RES = WIDTH, HEIGHT = 1280, 720
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60

# Player
PLAYER_POS = 1.5, 1.5
PLAYER_ANGLE = 0
PLAYER_SPEED = 2
PLAYER_ROT_SPEED = 2
PLAYER_MAX_HEALTH = 100

# Raycasting
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20
SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

# Textures
TEXTURE_SIZE = 256
WALL_BASE_HEIGHT = 1800
SPRITE_RATIO = 0.8
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
SPRITE_SCALE = 1.8
TILE_SIZE = 64

# Geisha
GEISHA_SPEED = 1.5
GEISHA_VISION_RANGE = 8